name: Build Bazzite Bifrost Image

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly automatic build
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Bazzite Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Image with BlueBuild
        uses: blue-build/github-action@v1
        with:
          recipe: recipe.yml
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          pr_event_number: ${{ github.event.number }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
